# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.webservice_user_provider:
        class: AppBundle\Security\User\WebserviceUserProvider
        arguments: ['@monolog.logger', '@app.recaptcha']
    app.recaptcha:
        class: AppBundle\Service\RecaptchaService
        arguments: ['@service_container']
    app.users.banned_listener:
        class: AppBundle\EventListener\BannedListener
        arguments: [@monolog.logger, @doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    app.users.tools:
        class: AppBundle\EventListener\ToolsListener
        arguments: [@monolog.logger, '%start_date%']
    app.command.update_fias:
        class: AppBundle\Command\UpdateFiasCommand
        arguments: ["update-fias"]
        tags:
            - { name: console.command }
    app.command.update_faq:
        class: AppBundle\Command\UpdateFAQCommand
        arguments: ["update-faq"]
        tags:
            - { name: console.command }
    app.command.update_winners:
        class: AppBundle\Command\UpdateWinnersCommand
        arguments: ["update-winners"]
        tags:
            - { name: console.command }
    app.command.update_gender:
        class: AppBundle\Command\UpdateGenderCommand
        arguments: ["update-gender"]
        tags:
            - { name: console.command }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
